name: CI

on:
  push:
    branches:
    - master
    paths:
    - "**/*.py"
  pull_request:
    branches:
    - master
    paths:
    - "**/*.py"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2.1.0
      with:
        poetry-version: 1.1.5
    - name: Install dependencies
      run: make install
    - name: Lint with flake8
      run: make lint
    - name: Typecheck with mypy
      run: make typecheck
    - name: Test with pytest
      run: make test
    - name: Measure coverage with Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./.report/coverage.xml
    - name: Build this package
      run: make build
