name: Release

on:
  push:
    tags:
    - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2.4.0
    - name: Set up Python
      uses: actions/setup-python@v2.3.1
      with:
        python-version: "3.10"
    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2.1.4
      with:
        poetry-version: 1.1.11
    - name: Publish to PyPI
      run: poetry publish --build --username __token__ --password ${{ secrets.PYPI_TOKEN }}
