name: Release

on:
  push:
    tags:
    - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.9
    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2.1.2
      with:
        poetry-version: 1.1.5
    - name: Publish to PyPI
      run: poetry publish --build --username __token__ --password ${{ secrets.PYPI_TOKEN }}
